use_frameworks!

target 'AFramework_Example' do
  pod 'AFramework', :path => '../'

   # 网络层框架 Carthage老出问题, Pods稳定, 快速
  # Moya ==========================================
  # Alamofire
  # Result
  # RxSwift
  # https://github.com/Moya/Moya
  pod 'Moya', '14.0.0'
  pod 'Moya/RxSwift', '14.0.0'
  # pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  # ===============================================
  
  # Kingfisher
  # 网络图片加载与缓存
  # https://github.com/onevcat/Kingfisher/releases
  pod "Kingfisher"

  
  # SwiftyUserDefaults
  # https://github.com/radex/SwiftyUserDefaults
  pod "SwiftyUserDefaults", "4.0.0"
  
  # SwiftyJSON
  # JSON处理
  # https://github.com/SwiftyJSON/SwiftyJSON/releases
  pod "SwiftyJSON"
  
  # IQKeyboardManager
  # 键盘管理
  # https://github.com/hackiftekhar/IQKeyboardManager/releases
  pod "IQKeyboardManagerSwift"
  
  # CryptoSwift
  # 加解密
  # https://github.com/krzyzanowskim/CryptoSwift/releases
  pod "CryptoSwift", "1.3.2"
  
  # SwiftyRSA
  # https://github.com/TakeScoop/SwiftyRSA
  pod "SwiftyRSA", "1.5.0"
  
  # reachable
  # https://github.com/ashleymills/Reachability.swift
  pod 'ReachabilitySwift'
  
  # SVProgressHUD
  # HUD
  # https://github.com/SVProgressHUD/SVProgressHUD/releases
  pod "SVProgressHUD"
  
  # yaml解析器
  # https://github.com/jpsim/Yams
  pod "Yams"
  
  # SnapKit
  # https://github.com/SnapKit/SnapKit
  pod "SnapKit", "5.0.1"
  
  # MJRefresh
  # 列表刷新控件
  # https://github.com/CoderMJLee/MJRefresh/releases
  pod "MJRefresh"
  
  # SwifterSwift
  # https://github.com/SwifterSwift/SwifterSwift
  # github "SwifterSwift/SwifterSwift" == 5.0.0
  pod "SwifterSwift", "5.2.0"
  
  # 考虑优化 ##############################
  # Cache
  # https://github.com/hyperoslo/Cache/releases
  # github "hyperoslo/Cache" ~> 6.0.0
  pod "Cache", "5.3.0"
  
  # Sheeeeeeeeet
  # https://github.com/danielsaidi/Sheeeeeeeeet
  pod 'Sheeeeeeeeet', '3.1.1'
  
  # 计划优化 ##############################
  # PopupDialog
  # https://github.com/Orderella/PopupDialog
  pod 'PopupDialog', '1.1.1'
  
  # Localize-Swift
  # https://github.com/marmelroy/Localize-Swift
  # github "marmelroy/Localize-Swift" ~> 2.0
  pod "Localize-Swift", "3.1.0"
  
  # EmptyDataSet
  # https://github.com/Xiaoye220/EmptyDataSet-Swift
  pod 'EmptyDataSet-Swift', '4.2.0'
  
  # SwiftyBeaver
  # 控制台美化
  # https://github.com/SwiftyBeaver/SwiftyBeaver/releases
  # github "SwiftyBeaver/SwiftyBeaver" == 1.7.0
  pod "SwiftyBeaver", "1.9.2"
  
  # 测试助手 =====================================================
  # https://github.com/didi/DoraemonKit
  pod 'DoraemonKit', '3.0.4', :configurations => ['Debug','Adhoc','Enterprise']
  # pod 'DoraemonKit/Core', '1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  # pod 'DoraemonKit/WithLogger', '1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  # pod 'DoraemonKit/WithGPS', '1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  # pod 'DoraemonKit/WithLoad', '1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  # ==============================================================
  
  target 'AFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
